apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary-test
  name: canary-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: canary-test
    spec:
      containers:
      - env:
        - name: EXAMPLE_HOST_URL
          value: http://inigo:8080
        image: iiglesias/indilab:simple-log-client0.1-SNAPSHOT
        imagePullPolicy: Always
        name: canary-test
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: canary-test
spec:
  selector:
    app: canary-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
